# Generated by Django 4.0.4 on 2022-04-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='images',
            new_name='image',
        ),
    ]
